- name: Meltdown and Spectre Detector
  hosts: web
  gather_facts: no
  tasks:
    - name: Check writable to store checker.
      stat:
        path: spectre-meltdown-checker/spectre-meltdown-checker.sh

    - name: copy checker.sh
      copy:
        src: spectre-meltdown-checker/spectre-meltdown-checker.sh
        dest: /tmp/spectre-meltdown-checker.sh

    - name: Permission the checker.sh file
      file:
        path: /tmp/spectre-meltdown-checker.sh
        mode: 0744
    
    - name: Run check variant 1~3 (Spectre & MeltDown)
      shell: /tmp/spectre-meltdown-checker.sh -n -d
      register: check
      failed_when: false
      changed_when: false
  
    - name: Result vulnerability variant 1~3 (Spectre & MeltDown)
      debug:
        var: check.stdout_lines
      changed_when: "'Vulnerable' in check.stdout"

    - name: Each Result Print
      debug: msg="{{ check.stdout | regex_findall("Variant*(.*)") }}"
